baseURL = 'https://drlzin.github.io/test/'
languageCode = 'pl'
title = 'Flary'

[taxonomies]
tag = 'tags'

[permalinks]
  posts = '/:year/:month/:day/:slug/'
  editions = '/wydania/:slug/'

[markup.goldmark.extensions.typographer]
leftDoubleQuote = '&bdquo;'
rightDoubleQuote = '&ldquo;'
leftSingleQuote = '&raquo;'
rightSingleQuote = '&laquo;'

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']

[params]
description = 'Rewolucja nie jest jabłkiem, które spada, kiedy jest dojrzałe. Trzeba sprawić, by spadło.'

